# GitHub Pages Configuration for Miguel Granado
title: "Miguel Granado - Estilista e Imagen Personal"
description: "La imagen no es solo cuestión de moda, sino de personalidad. Estudio de imagen y estilismo capilar en Buenos Aires"
author: "Miguel Granado"
url: "" # Will be auto-filled by GitHub Pages
baseurl: "" # Repository name (if not using username.github.io)

# GitHub Pages specific settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .git/
  - .nojekyll

# Include files that start with underscore
include:
  - .nojekyll

# Language and encoding
lang: es-AR
encoding: utf-8

# Social media and SEO
twitter:
  username: miguelgranado
  card: summary_large_image

facebook:
  app_id: ""

logo: /assets/favicon.svg

# Contact information for SEO
contact:
  phone: ""
  email: "turnos@granado.com.ar"
  address: "Av. Corrientes 1719 piso 6°, Buenos Aires, CABA"

# Site verification (add if needed)
google_site_verification: ""
bing_site_verification: "" 